# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Desktop/COD_Lab/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/ip/DataRAM/DataRAM.xci
# IP: The module: 'DataRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/COD_Lab/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/ip/DataRAM/DataRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Desktop/COD_Lab/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/ip/DataRAM/DataRAM.xci
# IP: The module: 'DataRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/COD_Lab/lab30_Risc5CPU/vivado201704/Risc5CPU.srcs/sources_1/ip/DataRAM/DataRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
