######################################################################
#
# File name : adder_32bits_tb.udo
# Created on: Sat Oct 29 13:19:44 +0800 2022
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
