######################################################################
#
# File name : adder_32bits_tb_compile.do
# Created on: Mon Oct 31 21:34:09 +0800 2022
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"adder_32bits_tb_time_impl.v" \
"../../../../../../src/adder_32bits_tb.v" \


quit -force

