######################################################################
#
# File name : adder_32bits_tb_simulate.do
# Created on: Mon Oct 31 21:34:12 +0800 2022
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vsim -voptargs="+acc" +transport_int_delays +pulse_e/0 +pulse_int_e/0 +pulse_r/0 +pulse_int_r/0 -L xil_defaultlib -L simprims_ver -L secureip -lib xil_defaultlib xil_defaultlib.adder_32bits_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {adder_32bits_tb_wave.do}

view wave
view structure
view signals

do {adder_32bits_tb.udo}

run 1000ns
